#!/usr/bin/env bash
# marina — 전역 dev 런처 + 관제 대시보드 진입점.
#
#   marina start|stop|restart|rebuild <svc..> # 현재 worktree(cwd) 의 서비스 (전체는 --all)
#   marina status | ports | logs [svc]       # 현재 worktree 상태/포트/로그
#   marina project {add|rm|ls|default|infer} # 프로젝트 레지스트리 (~/.marina/projects.json)
#   marina dashboard [start|stop|status|open]# 전역 대시보드(:3900). 무인자 marina = dashboard start
#
# 스크립트는 모두 이 파일의 형제(scripts/) — 어디서 실행하든 위치독립.

set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)"
SESSION="$SCRIPT_DIR/marina.sh"
DASHBOARD="$SCRIPT_DIR/marina-dashboard.sh"
ATTACH="$SCRIPT_DIR/attach-detached-subrepos.sh"
RESOLVE="$SCRIPT_DIR/marina-resolve.sh"
CLI="$SCRIPT_DIR/marina_cli.py"
# shellcheck source=/dev/null
source "$RESOLVE"

exec_session_with_env() {
  local py="${MARINA_PYTHON:-}"
  [[ -n "$py" ]] || py="$(command -v python3 || echo /usr/bin/python3)"
  exec "$py" "$CLI" exec "$@"
}

usage() {
  cat <<'EOF'
usage (marina = 전역 CLI):
  실행 (현재 worktree — 서비스명 그대로, 전체는 --all):
    marina start|stop|restart|rebuild <svc> # 예: marina rebuild web · 전체: marina start --all
    marina status | ports | logs [svc]
  프로젝트 등록 (~/.marina/projects.json — 위치 무관):
    marina project add <path> --compose <file>      # 기존 docker-compose 로 등록 (또는 대시보드 위저드)
    marina project add <path> --external name=path  # 외부 git 레포를 서비스로 (워크트리마다 격리)
    marina project ls | rm <id> | default <id> a,b,c | infer <path>
  워크트리 (작업 시작 — 브랜치명 지정 생성 + 서브레포 미러):
    marina worktree create <branch> [base] [--project <id>]
  게이트웨이 (호스트 브라우저 → <wt>.<proj>.localhost, 보통 start 시 자동 기동):
    marina gateway start|stop|status|config|install|uninstall
  링크 (main checkout 의 deps·빌드산출물·설정을 워크트리로):
    marina link
  dashboard (:3900):
    marina dashboard [start|stop|status|open]    # 무인자 marina = dashboard start
  setup: marina attach | install-cli | uninstall-cli
EOF
}

print_dashboard_url() {
  echo
  echo "Dashboard: http://${MARINA_CONTROL_HOST:-localhost}:${MARINA_CONTROL_PORT:-3900}"
  echo
}

command="${1:-dashboard}"
shift || true

case "$command" in
  project|worktree|gateway|link)
    # 그룹 → marina.sh dispatch 로 위임 (project {add|rm|ls|...} · worktree create · gateway {start|...} · link)
    # worktree/gateway 누락이 "설치 shim 은 이 명령 없음" 증상의 원인이었음(도그푸드에서 발견)
    "$SESSION" "$command" "$@"
    ;;
  start|stop|restart|rebuild)
    # bare 서비스명(web)을 marina.sh 가 받는 --flag 로 변환. 이미 --(--all 등)는 그대로 패스.
    # 무인자는 변환 결과도 빈 인자 → marina.sh 무인자 가드(usage·exit 2)에 위임.
    lifecycle_args=()
    for arg in "$@"; do
      case "$arg" in
        --*) lifecycle_args+=("$arg") ;;
        *)   lifecycle_args+=("--$arg") ;;
      esac
    done
    exec_session_with_env "$command" ${lifecycle_args[@]+"${lifecycle_args[@]}"}
    ;;
  status|ports|logs)
    # 변환 불요(단일/무인자)
    exec_session_with_env "$command" "$@"
    ;;
  dashboard)
    case "${1:-start}" in
      start|"") "$DASHBOARD" start; print_dashboard_url ;;
      stop)     "$DASHBOARD" stop ;;
      status)   "$DASHBOARD" status ;;
      open)     shift; exec "$0" open ;;
      *) echo "usage: marina dashboard {start|stop|status|open}" >&2; exit 2 ;;
    esac
    ;;
  open)
    url="http://${MARINA_CONTROL_HOST:-localhost}:${MARINA_CONTROL_PORT:-3900}"
    if command -v open >/dev/null 2>&1; then open "$url"        # macOS
    elif command -v xdg-open >/dev/null 2>&1; then xdg-open "$url"  # Linux
    else echo "$url"
    fi
    ;;
  attach|prepare)
    "$ATTACH"
    ;;
  -h|--help|help)
    usage
    ;;
  install-cli)
    bindir="${MARINA_BIN_DIR:-$HOME/.local/bin}"; target="$bindir/marina"
    if [[ -e "$target" ]] && ! grep -q 'AUTO-GENERATED by marina' "$target" 2>/dev/null && [[ "${1:-}" != "--force" ]]; then
      echo "error: $target exists and is not a marina shim (use --force)" >&2; exit 1
    fi
    marina_emit_launcher "$target" entrypoint
    echo "installed: $target"
    case ":$PATH:" in
      *":$bindir:"*) : ;;
      *) echo; echo "note: $bindir is not on PATH. Add:"; echo "  export PATH=\"$bindir:\$PATH\"" ;;
    esac
    ;;
  uninstall-cli)
    target="${MARINA_BIN_DIR:-$HOME/.local/bin}/marina"
    if [[ -e "$target" ]] && grep -q 'AUTO-GENERATED by marina' "$target" 2>/dev/null; then
      rm -f "$target"; echo "removed: $target"
    else
      echo "nothing to remove (not a marina shim): $target"
    fi
    ;;
  *)
    echo "error: unknown command: $command" >&2
    usage >&2
    exit 1
    ;;
esac
