#!/usr/bin/env bash
# marina-resolve.sh — sourced by in-plugin scripts. Emitted launchers EMBED the resolution + a baked fallback
# (they live outside the plugin, so they can't source this).
#
# Install layouts differ by harness:
#   Claude — ~/.claude/plugins/installed_plugins.json → installPath = <cache>/marina/<sha> (scripts/ at root)
#   Codex  — ~/.codex/config.toml [marketplaces.marina-dev] source = <marketplace dir>; plugin lives at <source>/plugin
# We never trust a single manifest: gather candidates, then pick the one that actually has scripts/marina-entrypoint.sh.

# Print current install dir for marina@marina-dev (dir containing scripts/), or non-zero if none resolves.
marina_install_path() {
  python3 - <<'PY'
import json, os, re, sys
def ok(p):
    p = os.path.expanduser(p or "")
    return bool(p) and os.path.isfile(os.path.join(p, "scripts", "marina-entrypoint.sh"))
def is_dev(p):
    p = os.path.realpath(os.path.expanduser(p or ""))
    git = os.path.join(os.path.dirname(p), ".git")
    return os.path.basename(p) == "plugin" and (os.path.isdir(git) or os.path.isfile(git))
cands = []
if len(sys.argv) > 1 and sys.argv[1] and is_dev(sys.argv[1]):
    cands.append(sys.argv[1])   # source checkout launcher: keep serving the editable dev tree
for mf in [os.path.expanduser(os.environ.get("CLAUDE_CONFIG_DIR", "~/.claude") + "/plugins/installed_plugins.json"),
           os.path.expanduser(os.environ.get("CODEX_HOME", "~/.codex") + "/plugins/installed_plugins.json")]:
    try:
        cands.append(json.load(open(mf, encoding="utf-8"))["plugins"]["marina@marina-dev"][0]["installPath"])
    except Exception:
        pass
try:   # Codex: config.toml marketplace source → plugin is at <source>/plugin
    t = open(os.path.expanduser(os.environ.get("CODEX_HOME", "~/.codex") + "/config.toml"), encoding="utf-8").read()
    m = re.search(r"\[marketplaces\.marina-dev\](.*?)(?=\n\[|\Z)", t, re.S)
    s = re.search(r'source\s*=\s*"([^"]+)"', m.group(1)) if m else None
    if s:
        cands += [os.path.join(s.group(1), "plugin"), s.group(1)]
except Exception:
    pass
for c in cands:
    if ok(c):
        print(os.path.expanduser(c)); sys.exit(0)
sys.exit(1)
PY
}

# Write a self-contained launcher to $1. $2 = exec kind: "entrypoint" | "dashboard".
# Re-resolves on every run (survives auto-update) AND keeps the install-time path as a fallback
# (survives Codex layout, non-default CLAUDE_CONFIG_DIR/CODEX_HOME, and a missing/renamed manifest).
# 그 경로는 런처 안이 아니라 옆 파일(<런처>.path)에 둔다 — 버전 폴더가 런처에 박히면 업데이트마다 런처 내용이 달라지고,
# macOS 는 로그인 항목의 실행 파일이 바뀌었다고 "백그라운드 항목이 추가됨" 알림을 띄운다(2026-10-06).
marina_emit_launcher() {
  local target="$1" kind="$2" exec_line baked need="marina-entrypoint.sh"
  baked="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." 2>/dev/null && pwd -P)"   # emit 시점 plugin dir
  case "$kind" in
    entrypoint) exec_line='exec "$ip/scripts/marina-entrypoint.sh" "$@"' ;;
    dashboard)  exec_line='exec "${MARINA_PYTHON:-$(command -v python3 || echo /usr/bin/python3)}" "$ip/scripts/marina-control.py"' ;;
    runtimed)   exec_line='exec "${MARINA_PYTHON:-$(command -v python3 || echo /usr/bin/python3)}" "$ip/scripts/marina_runtimed.py"'
                need="marina_runtimed.py" ;;   # 옛 설치본(이 파일 없음)을 고르지 않게
    *) echo "marina_emit_launcher: bad kind: $kind" >&2; return 2 ;;
  esac
  mkdir -p "$(dirname "$target")"
  printf '%s\n' "$baked" > "$target.path"
  local tmp; tmp="$(mktemp "$target.XXXXXX")" || return 1
  cat > "$tmp" <<EOF || { rm -f "$tmp"; return 1; }
#!/usr/bin/env bash
# AUTO-GENERATED by marina. Re-resolves the current plugin (Claude/Codex); falls back to the install-time path ($target.path).
set -euo pipefail
ip="\$(python3 - "\$(cat "$target.path" 2>/dev/null || true)" "$need" <<'PY'
import json, os, re, sys
NEED = sys.argv[2] if len(sys.argv) > 2 else "marina-entrypoint.sh"
def ok(p):
    p = os.path.expanduser(p or "")
    return bool(p) and os.path.isfile(os.path.join(p, "scripts", "marina-entrypoint.sh")) and os.path.isfile(os.path.join(p, "scripts", NEED))
def is_dev(p):
    p = os.path.realpath(os.path.expanduser(p or ""))
    git = os.path.join(os.path.dirname(p), ".git")
    return os.path.basename(p) == "plugin" and (os.path.isdir(git) or os.path.isfile(git))
cands = []
if len(sys.argv) > 1 and is_dev(sys.argv[1]):
    cands.append(sys.argv[1])   # source checkout launcher: keep serving the editable dev tree
for mf in [os.path.expanduser(os.environ.get("CLAUDE_CONFIG_DIR", "~/.claude") + "/plugins/installed_plugins.json"),
           os.path.expanduser(os.environ.get("CODEX_HOME", "~/.codex") + "/plugins/installed_plugins.json")]:
    try:
        cands.append(json.load(open(mf, encoding="utf-8"))["plugins"]["marina@marina-dev"][0]["installPath"])
    except Exception:
        pass
try:
    t = open(os.path.expanduser(os.environ.get("CODEX_HOME", "~/.codex") + "/config.toml"), encoding="utf-8").read()
    m = re.search(r"\[marketplaces\.marina-dev\](.*?)(?=\n\[|\Z)", t, re.S)
    s = re.search(r'source\s*=\s*"([^"]+)"', m.group(1)) if m else None
    if s:
        cands += [os.path.join(s.group(1), "plugin"), s.group(1)]
except Exception:
    pass
if len(sys.argv) > 1 and sys.argv[1] and not is_dev(sys.argv[1]):
    cands.append(sys.argv[1])   # 설치 시점 경로(fallback)
for c in cands:
    if ok(c):
        print(os.path.expanduser(c)); sys.exit(0)
sys.exit(1)
PY
)" || { echo "marina: cannot locate installed plugin (marina@marina-dev). Reinstall or set CLAUDE_CONFIG_DIR/CODEX_HOME." >&2; exit 1; }
$exec_line
EOF
  chmod 755 "$tmp"
  # 내용이 같으면 그대로 둔다(파일 시각도 안 바뀐다) — 로그인 항목의 실행 파일이다
  if cmp -s "$tmp" "$target" && [[ -x "$target" ]]; then rm -f "$tmp"; else mv -f "$tmp" "$target"; fi
}
