#!/usr/bin/env bash
# marina-resolve.sh — sourced by in-plugin scripts. NEVER sourced by emitted launchers
# (they live outside the plugin); instead they embed the resolution snippet below.

# Ordered manifest candidates: Claude first, then Codex (best-effort; verify on a Codex box).
marina_manifest_candidates() {
  printf '%s\n' \
    "${CLAUDE_CONFIG_DIR:-$HOME/.claude}/plugins/installed_plugins.json" \
    "${CODEX_HOME:-$HOME/.codex}/plugins/installed_plugins.json"
}

# Print current install path for marina@marina-dev, or non-zero if not found.
marina_install_path() {
  local mf
  while IFS= read -r mf; do
    [[ -f "$mf" ]] || continue
    python3 - "$mf" <<'PY' && return 0
import json, sys
try:
    d = json.load(open(sys.argv[1], encoding="utf-8"))
    print(d["plugins"]["marina@marina-dev"][0]["installPath"])
except Exception:
    sys.exit(1)
PY
  done < <(marina_manifest_candidates)
  return 1
}

# Write a self-contained launcher to $1. $2 = exec kind: "entrypoint" | "dashboard".
# The emitted file re-resolves the install path on every invocation (survives auto-update).
marina_emit_launcher() {
  local target="$1" kind="$2" exec_line
  case "$kind" in
    entrypoint) exec_line='exec "$ip/scripts/marina-entrypoint.sh" "$@"' ;;
    dashboard)  exec_line='exec "${MARINA_PYTHON:-$(command -v python3 || echo /usr/bin/python3)}" "$ip/scripts/marina-control.py"' ;;
    *) echo "marina_emit_launcher: bad kind: $kind" >&2; return 2 ;;
  esac
  mkdir -p "$(dirname "$target")"
  cat > "$target" <<EOF
#!/usr/bin/env bash
# AUTO-GENERATED by marina. Re-resolves the current plugin version on every run.
set -euo pipefail
ip="\$(python3 - <<'PY'
import json, os, sys
cands = [
    os.path.expanduser(os.environ.get("CLAUDE_CONFIG_DIR", "~/.claude") + "/plugins/installed_plugins.json"),
    os.path.expanduser(os.environ.get("CODEX_HOME", "~/.codex") + "/plugins/installed_plugins.json"),
]
for mf in cands:
    try:
        d = json.load(open(mf, encoding="utf-8"))
        print(d["plugins"]["marina@marina-dev"][0]["installPath"]); sys.exit(0)
    except Exception:
        continue
sys.exit(1)
PY
)" || { echo "marina: cannot locate installed plugin (is marina@marina-dev installed?)" >&2; exit 1; }
$exec_line
EOF
  chmod +x "$target"
}
