#!/usr/bin/env bash
# marina-resolve.sh — sourced by in-plugin scripts. Emitted launchers EMBED the resolution + a baked fallback
# (they live outside the plugin, so they can't source this).
#
# Install layouts differ by harness:
#   Claude — ~/.claude/plugins/installed_plugins.json → installPath = <cache>/marina/<sha> (scripts/ at root)
#   Codex  — ~/.codex/config.toml [marketplaces.marina-dev] source = <marketplace dir>; plugin lives at <source>/plugin
# We never trust a single manifest: gather candidates, then pick the one that actually has scripts/marina-entrypoint.sh.

# Print current install dir for marina@marina-dev (dir containing scripts/), or non-zero if none resolves.
marina_install_path() {
  python3 - <<'PY'
import json, os, re, sys
def ok(p):
    p = os.path.expanduser(p or "")
    return bool(p) and os.path.isfile(os.path.join(p, "scripts", "marina-entrypoint.sh"))
def is_dev(p):
    p = os.path.realpath(os.path.expanduser(p or ""))
    git = os.path.join(os.path.dirname(p), ".git")
    return os.path.basename(p) == "plugin" and (os.path.isdir(git) or os.path.isfile(git))
cands = []
if len(sys.argv) > 1 and is_dev(sys.argv[1]):
    cands.append(sys.argv[1])   # source checkout launcher: keep serving the editable dev tree
for mf in [os.path.expanduser(os.environ.get("CLAUDE_CONFIG_DIR", "~/.claude") + "/plugins/installed_plugins.json"),
           os.path.expanduser(os.environ.get("CODEX_HOME", "~/.codex") + "/plugins/installed_plugins.json")]:
    try:
        cands.append(json.load(open(mf, encoding="utf-8"))["plugins"]["marina@marina-dev"][0]["installPath"])
    except Exception:
        pass
try:   # Codex: config.toml marketplace source → plugin is at <source>/plugin
    t = open(os.path.expanduser(os.environ.get("CODEX_HOME", "~/.codex") + "/config.toml"), encoding="utf-8").read()
    m = re.search(r"\[marketplaces\.marina-dev\](.*?)(?=\n\[|\Z)", t, re.S)
    s = re.search(r'source\s*=\s*"([^"]+)"', m.group(1)) if m else None
    if s:
        cands += [os.path.join(s.group(1), "plugin"), s.group(1)]
except Exception:
    pass
for c in cands:
    if ok(c):
        print(os.path.expanduser(c)); sys.exit(0)
sys.exit(1)
PY
}

# Write a self-contained launcher to $1. $2 = exec kind: "entrypoint" | "dashboard".
# Re-resolves on every run (survives auto-update) AND bakes the install-time path as a fallback
# (survives Codex layout, non-default CLAUDE_CONFIG_DIR/CODEX_HOME, and a missing/renamed manifest).
marina_emit_launcher() {
  local target="$1" kind="$2" exec_line baked
  baked="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." 2>/dev/null && pwd -P)"   # emit 시점 plugin dir
  case "$kind" in
    entrypoint) exec_line='exec "$ip/scripts/marina-entrypoint.sh" "$@"' ;;
    dashboard)  exec_line='exec "${MARINA_PYTHON:-$(command -v python3 || echo /usr/bin/python3)}" "$ip/scripts/marina-control.py"' ;;
    *) echo "marina_emit_launcher: bad kind: $kind" >&2; return 2 ;;
  esac
  mkdir -p "$(dirname "$target")"
  cat > "$target" <<EOF
#!/usr/bin/env bash
# AUTO-GENERATED by marina. Re-resolves the current plugin (Claude/Codex); falls back to the install-time path.
set -euo pipefail
ip="\$(python3 - "$baked" <<'PY'
import json, os, re, sys
def ok(p):
    p = os.path.expanduser(p or "")
    return bool(p) and os.path.isfile(os.path.join(p, "scripts", "marina-entrypoint.sh"))
def is_dev(p):
    p = os.path.realpath(os.path.expanduser(p or ""))
    git = os.path.join(os.path.dirname(p), ".git")
    return os.path.basename(p) == "plugin" and (os.path.isdir(git) or os.path.isfile(git))
cands = []
if len(sys.argv) > 1 and is_dev(sys.argv[1]):
    cands.append(sys.argv[1])   # source checkout launcher: keep serving the editable dev tree
for mf in [os.path.expanduser(os.environ.get("CLAUDE_CONFIG_DIR", "~/.claude") + "/plugins/installed_plugins.json"),
           os.path.expanduser(os.environ.get("CODEX_HOME", "~/.codex") + "/plugins/installed_plugins.json")]:
    try:
        cands.append(json.load(open(mf, encoding="utf-8"))["plugins"]["marina@marina-dev"][0]["installPath"])
    except Exception:
        pass
try:
    t = open(os.path.expanduser(os.environ.get("CODEX_HOME", "~/.codex") + "/config.toml"), encoding="utf-8").read()
    m = re.search(r"\[marketplaces\.marina-dev\](.*?)(?=\n\[|\Z)", t, re.S)
    s = re.search(r'source\s*=\s*"([^"]+)"', m.group(1)) if m else None
    if s:
        cands += [os.path.join(s.group(1), "plugin"), s.group(1)]
except Exception:
    pass
if len(sys.argv) > 1 and sys.argv[1] and not is_dev(sys.argv[1]):
    cands.append(sys.argv[1])   # 설치 시점 경로(fallback)
for c in cands:
    if ok(c):
        print(os.path.expanduser(c)); sys.exit(0)
sys.exit(1)
PY
)" || { echo "marina: cannot locate installed plugin (marina@marina-dev). Reinstall or set CLAUDE_CONFIG_DIR/CODEX_HOME." >&2; exit 1; }
$exec_line
EOF
  chmod +x "$target"
}
