#!/usr/bin/env bash
set -euo pipefail
HERE="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)"
ENTRY="$HERE/../scripts/marina-entrypoint.sh"
TMP="$(mktemp -d)"; trap 'rm -rf "$TMP"' EXIT
export MARINA_BIN_DIR="$TMP/bin"
export PATH="/usr/bin:/bin"   # MARINA_BIN_DIR deliberately NOT on PATH

out="$(bash "$ENTRY" install-cli 2>&1)"
[[ -x "$TMP/bin/marina" ]] || { echo "FAIL: shim not installed"; exit 1; }
grep -q 'AUTO-GENERATED by marina' "$TMP/bin/marina" || { echo "FAIL: not a marina shim"; exit 1; }
echo "$out" | grep -qi 'PATH' || { echo "FAIL: missing PATH warning"; exit 1; }

bash "$ENTRY" uninstall-cli >/dev/null 2>&1
[[ ! -e "$TMP/bin/marina" ]] || { echo "FAIL: shim not removed"; exit 1; }
echo "PASS test-install-cli"
